services:
  money-manager:
    restart: always
    build: .
    image: money-manager:latest  # Make sure this is the correct tag
    container_name: money-manager
    # ports:
    #   - 3000:3000
    networks:
      - proxy
      - database
    env_file:
      - .env.production
    environment:
      HOSTNAME: 0.0.0.0
      PORT: 3000
  database:
    image: postgres:16
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      DATABASE_HOST: database
      POSTGRES_DB: money_manager
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env.production
    # Only uncomment this to expose the database for direct access
    # ports:
    #   - 5431:5432
    networks:
      - proxy
      - database
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
networks:
  proxy:
    external: true
  database:
    driver: bridge

volumes:
  db_data:
    driver: local