services:
  database:
    image: postgres:16
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      DATABASE_HOST: database
      POSTGRES_DB: money_manager
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # Only uncomment this to expose the database for direct access
    ports:
      - 5432:5432
    networks:
      - database
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

networks:
  database:
    driver: bridge

volumes:
  db_data:
    driver: local
